ALTER TABLE HopDong
    ADD CONSTRAINT FK_HopDong_KhachHang FOREIGN KEY (MaKH) REFERENCES KhachHang (MaKH);
ALTER TABLE HoaDon
    ADD CONSTRAINT FK_HoaDon_KhachHang FOREIGN KEY (MaKH) REFERENCES KhachHang (MaKH);

ALTER TABLE PhieuThue
    ADD CONSTRAINT FK_PhieuThue_KhachHang FOREIGN KEY (MaKH) REFERENCES KhachHang (MaKH);

ALTER TABLE HopDong
    ADD CONSTRAINT FK_HopDong_NhaChoThue FOREIGN KEY (MaNha) REFERENCES NhaChoThue (MaNha);

ALTER TABLE HoaDon
    ADD CONSTRAINT FK_HoaDon_NhaChoThue FOREIGN KEY (MaNha) REFERENCES NhaChoThue (MaNha);

ALTER TABLE PhieuThue
    ADD CONSTRAINT FK_PhieuThue_NhaChoThue FOREIGN KEY (MaNha) REFERENCES NhaChoThue (MaNha);
