ALTER TABLE KhachHang
    ADD CONSTRAINT UC_SoDienThoai UNIQUE (SoDienThoai);

ALTER TABLE NhaChoThue
    ADD CONSTRAINT CK_TinhTrang CHECK (TinhTrang IN ('Có sẵn', 'Đã thuê', 'Đang bảo trì'));

ALTER TABLE HopDong
    ADD CONSTRAINT FK_HopDong_MaNha FOREIGN KEY (MaNha) REFERENCES NhaChoThue(MaNha) ON DELETE CASCADE,
    ADD CONSTRAINT FK_HopDong_MaKH FOREIGN KEY (MaKH) REFERENCES KhachHang(MaKH) ON DELETE CASCADE;

ALTER TABLE HoaDon
    ADD CONSTRAINT FK_HoaDon_MaKH FOREIGN KEY (MaKH) REFERENCES KhachHang(MaKH),
    ADD CONSTRAINT FK_HoaDon_MaNha FOREIGN KEY (MaNha) REFERENCES NhaChoThue(MaNha),
    ADD CONSTRAINT FK_HoaDon_MaPT FOREIGN KEY (MaPT) REFERENCES PhieuThue(MaPT) ON DELETE CASCADE;

ALTER TABLE PhieuDichVu
    ADD CONSTRAINT FK_PhieuDichVu_MaPT FOREIGN KEY (MaPT) REFERENCES PhieuThue(MaPT) ON DELETE CASCADE,
    ADD CONSTRAINT FK_PhieuDichVu_MaDV FOREIGN KEY (MaDV) REFERENCES DichVu(MaDV) ON DELETE CASCADE;

ALTER TABLE PhieuThue
    ADD CONSTRAINT CK_PhuongThuc CHECK (NgayBatDau < NgayKetThuc),
    ADD CONSTRAINT FK_PhieuThue_MaNha FOREIGN KEY (MaNha) REFERENCES NhaChoThue(MaNha) ON DELETE CASCADE,
    ADD CONSTRAINT FK_PhieuThue_MaKH FOREIGN KEY (MaKH) REFERENCES KhachHang(MaKH) ON DELETE CASCADE;

ALTER TABLE DichVu
    ADD CONSTRAINT CK_GiaDV CHECK (GiaDV > 0);
