DROP DATABASE IF EXISTS DB04;
CREATE DATABASE DB04;
USE DB04;

DROP TABLE IF EXISTS PhieuDichVu;
DROP TABLE IF EXISTS PhieuThue;
DROP TABLE IF EXISTS HoaDon;
DROP TABLE IF EXISTS HopDong;
DROP TABLE IF EXISTS NhaChoThue;
DROP TABLE IF EXISTS KhachHang;
DROP TABLE IF EXISTS DichVu;

CREATE TABLE KhachHang (
    MaKH INT PRIMARY KEY AUTO_INCREMENT,
    HoTen VARCHAR(100) NOT NULL,
    SoDienThoai VARCHAR(15) NOT NULL UNIQUE,
    CoQuan VARCHAR(100)
);

CREATE TABLE NhaChoThue (
    MaNha INT PRIMARY KEY AUTO_INCREMENT,
    DiaChi VARCHAR(255),
    GiaThue DECIMAL(10, 2),
    TenChuNha VARCHAR(100),
    TinhTrang ENUM('Có sẵn', 'Đã thuê', 'Đang bảo trì') NOT NULL
);

CREATE TABLE HopDong (
    MaNha INT,
    MaKH INT,
    NgayBatDau DATE,
    NgayKetThuc DATE,
    PRIMARY KEY (MaNha, MaKH),
    FOREIGN KEY (MaNha) REFERENCES NhaChoThue(MaNha) ON DELETE CASCADE,
    FOREIGN KEY (MaKH) REFERENCES KhachHang(MaKH) ON DELETE CASCADE,
    CHECK (NgayBatDau < NgayKetThuc)
);

CREATE TABLE PhieuThue (
    MaPT INT PRIMARY KEY AUTO_INCREMENT,
    MaNha INT,
    MaKH INT,
    NgayBatDau DATE,
    NgayKetThuc DATE,
    GiaThue DECIMAL(10, 2),
    FOREIGN KEY (MaNha) REFERENCES NhaChoThue(MaNha) ON DELETE CASCADE,
    FOREIGN KEY (MaKH) REFERENCES KhachHang(MaKH) ON DELETE CASCADE,
    CHECK (NgayBatDau < NgayKetThuc)
);
CREATE TABLE HoaDon (
    MaHD INT PRIMARY KEY AUTO_INCREMENT,
    MaKH INT,
    MaNha INT,
    MaPT INT,
    NgayLap DATE,
    FOREIGN KEY (MaKH) REFERENCES KhachHang(MaKH) ON DELETE CASCADE,
    FOREIGN KEY (MaNha) REFERENCES NhaChoThue(MaNha) ON DELETE CASCADE,
    FOREIGN KEY (MaPT) REFERENCES PhieuThue(MaPT) ON DELETE CASCADE
);

CREATE TABLE DichVu (
    MaDV INT PRIMARY KEY AUTO_INCREMENT,
    TenDV VARCHAR(100) NOT NULL,
    GiaDV DECIMAL(10, 2) NOT NULL
);

CREATE TABLE PhieuDichVu (
    MaPhieuDV INT PRIMARY KEY AUTO_INCREMENT,
    MaPT INT,
    MaDV INT,
    NgayLap DATE,
    ThanhTien DECIMAL(15, 2),
    FOREIGN KEY (MaPT) REFERENCES PhieuThue(MaPT) ON DELETE CASCADE,
    FOREIGN KEY (MaDV) REFERENCES DichVu(MaDV) ON DELETE CASCADE
);

